[project]
name = 'with-err'
version = '1.1.0'
description = 'converting `try-except` pattern to Go-like `result, err` pattern.'
readme = 'README.md'
license = 'MIT'
authors = [
    {name = 'Chuan-Heng Hsiao', email = 'hsiao.chuanheng@gmail.com'},
]
requires-python = '>=3.12'
dependencies = [
]
keywords = [
]
classifiers = [
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
]

[project.urls]
# Homepage      = ''
# Documentation = ''
Repository = 'https://github.com/chhsiao1981/with-err'
# 'Bug Tracker' = ''
# Changelog = ''

[project.scripts]

[build-system]
requires = [
    'uv_build>=0.12.5,<0.13.0',
]
build-backend = 'uv_build'

[dependency-groups]
dev = [
    'ruff==0.16.3',          # use ruff check --fix, not ruff format.
    'pytest==9.1.1',
    'pytest-asyncio==1.4.0',
    'pytest-cov==7.1.0',
    'lefthook==2.1.10',
    'autopep8==2.3.2',       # autopep8 is better in whitespace formatting.
]

[tool.autopep8]
max_line_length = 100

[tool.ruff]
line-length = 100
preview     = true

[tool.ruff.lint]
extend-select = [
    'E',
    'W',
]
