name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          src: "./src"
      - name: Lint
        run: bash scripts/lint.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Sync
        run: uv sync
      - name: Test
        run: bash scripts/test.sh
